CREATE TABLE Major_Courses (
id int NOT NULL, 
Course_ID VARCHAR(255),
FOREIGN KEY (id) references Majors (ID),
FOREIGN KEY (Course_ID) references Courses(Course_ID)
);

INSERT INTO Major_Courses 
VALUES 
((SELECT ID FROM Majors WHERE Major_Name = 'Accounting'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Accounting'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Accounting'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Accounting'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Accounting'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Accounting'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Accounting'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Accounting'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Accounting'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Administrative Office Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Administrative Office Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Administrative Office Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Administrative Office Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Administrative Office Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Administrative Office Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Administrative Office Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Administrative Office Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Administrative Office Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Aircraft Maintenance Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Aircraft Maintenance Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Aircraft Maintenance Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Aircraft Maintenance Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Aircraft Maintenance Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Aircraft Maintenance Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Aircraft Maintenance Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Aircraft Maintenance Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Aircraft Maintenance Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Baking and Pastry Arts'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Baking and Pastry Arts'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Baking and Pastry Arts'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Baking and Pastry Arts'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Baking and Pastry Arts'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Baking and Pastry Arts'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Baking and Pastry Arts'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Baking and Pastry Arts'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Baking and Pastry Arts'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Business Administration'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Business Administration'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Business Administration'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Business Administration'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Business Administration'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Business Administration'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Business Administration'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Business Administration'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Business Administration'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Civil Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Civil Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Civil Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Civil Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Civil Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Civil Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Civil Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Civil Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Civil Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Commercial Graphics'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Commercial Graphics'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Commercial Graphics'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Commercial Graphics'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Commercial Graphics'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Commercial Graphics'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Commercial Graphics'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Commercial Graphics'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Commercial Graphics'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Computer Programming'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Computer Programming'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Computer Programming'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Computer Programming'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Computer Programming'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Computer Programming'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Computer Programming'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Computer Programming'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Computer Programming'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Information Systems Specialist'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Information Systems Specialist'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Information Systems Specialist'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Information Systems Specialist'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Information Systems Specialist'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Information Systems Specialist'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Information Systems Specialist'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Information Systems Specialist'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Information Systems Specialist'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST105')),
((SELECT ID FROM Majors WHERE Major_Name = 'General Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'General Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'General Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'General Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'General Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN101')),
((SELECT ID FROM Majors WHERE Major_Name = 'General Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN102')),
((SELECT ID FROM Majors WHERE Major_Name = 'General Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN103')),
((SELECT ID FROM Majors WHERE Major_Name = 'General Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN104')),
((SELECT ID FROM Majors WHERE Major_Name = 'General Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Mechanical Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'Mechanical Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Mechanical Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Mechanical Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Mechanical Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Mechanical Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Mechanical Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Mechanical Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Mechanical Engineering Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Network Systems Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'Network Systems Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Network Systems Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Network Systems Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Network Systems Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Network Systems Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Network Systems Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Network Systems Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Network Systems Management'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Occupational Therapy Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'Occupational Therapy Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Occupational Therapy Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Occupational Therapy Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Occupational Therapy Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Occupational Therapy Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Occupational Therapy Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Occupational Therapy Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Occupational Therapy Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Physical Therapist Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'Physical Therapist Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Physical Therapist Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Physical Therapist Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Physical Therapist Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Physical Therapist Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Physical Therapist Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Physical Therapist Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Physical Therapist Assistant'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA105')),
((SELECT ID FROM Majors WHERE Major_Name = 'Veterinary Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'Veterinary Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Veterinary Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Veterinary Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Veterinary Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET101')),
((SELECT ID FROM Majors WHERE Major_Name = 'Veterinary Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET102')),
((SELECT ID FROM Majors WHERE Major_Name = 'Veterinary Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET103')),
((SELECT ID FROM Majors WHERE Major_Name = 'Veterinary Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET104')),
((SELECT ID FROM Majors WHERE Major_Name = 'Veterinary Technology'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET105')),

((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA105')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),#
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET101')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET102')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET103')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET104')),
((SELECT ID FROM Majors WHERE Major_Name = 'All Courses'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET105'));


CREATE TABLE Courses_Prereq ( 
id VARCHAR(255),
Course_Prereq VARCHAR(255),
FOREIGN KEY (id) references Courses (Course_ID),
FOREIGN KEY (Course_Prereq) references Courses(Course_ID)
);

insert into Courses
values
('CPT102',   'Advanced Java Programming'),
('CPT103',  'Super Advanced Java Programming'),
('CPT104',  'Giga Advanced Java Programming'),
('CPT105',  'Omega Advanced Java Programming'),
('ACC102',  'Advanced Accounting'),
('ACC103',  'Super Advanced Accounting'),
('ACC104',  'Giga Advanced Accounting'),
('ACC105',  'Omega Advanced Accounting'),
('ADM102',  'Advanced Administrating'),
('ADM103',  'Super Advanced Administrating'),
('ADM104',  'Giga Advanced Administrating'),
('ADM105',  'Omega Advanced Administrating'),
('AMT102',  'Advanced Aircraft Building'),
('AMT103',  'Super Advanced Aircraft Building'),
('AMT104',  'Giga Advanced Aircraft Building'),
('AMT105',  'Omega Advanced Aircraft Building'),
('BAK102',  'Advanced Cake Conceptualizing'),
('BAK103',  'Super Advanced Cake Conceptualizing'),
('BAK104',  'Giga Advanced Cake Conceptualizing'),
('BAK105',  'Omega Advanced Cake Conceptualizing'),
('BIS102',  'Advanced Acronym Making'),
('BIS103',  'Super Advanced Acronym Making'),
('BIS104',  'Giga Advanced Acronym Making'),
('BIS105',  'Omega Advanced Acronym Making'),
('CET102', 'Advanced Back Pat Lecture'),
('CET103', 'Super Advanced Back Pat Lecture'),
('CET104', 'Giga Advanced Back Pat Lecture'),
('CET105', 'Omega Advanced Back Pat Lecture'),
('CAD102',  'Advanced Tracing'),
('CAD103',  'Super Advanced Tracing'),
('CAD104',  'Giga Advanced Tracing'),
('CAD105',  'Omega Advanced Tracing'),
('IST102',  'Advanced CAT5 Identification'),
('IST102',  'Super Advanced CAT5 Identification'),
('IST102',  'Giga Advanced CAT5 Identification'),
('IST102',  'Omega Advanced CAT5 Identification'),
('GEN102',  'Advanced technology in the field'),
('GEN103',  'Super Advanced technology in the field'),
('GEN104',  'Giga Advanced technology in the field'),
('GEN105',  'Omega Advanced technology in the field'),
('MGT102',  'Advanced Micromanaging'),
('MGT103',  'Super Advanced Micromanaging'),
('MGT104',  'Giga Advanced Micromanaging'),
('MGT105',  'Omega Advanced Micromanaging'),
('MET102',  'Advanced 3D pen usage'),
('MET103',  'Super Advanced 3D pen usage'),
('MET104',  'Giga Advanced 3D pen usage'),
('MET105',  'Omega Advanced 3D pen usage'),
('NSM102',  'Advanced How to Not Get Zapped'),
('NSM103',  'Super Advanced How to Not Get Zapped'),
('NSM104',  'Giga Advanced How to Not Get Zapped'),
('NSM105',  'Omega Advanced How to Not Get Zapped'),
('OTA102', 'Advanced Feeling Good About Your Job'),
('OTA103', 'Super Advanced Feeling Good About Your Job'),
('OTA104', 'Giga Advanced Feeling Good About Your Job'),
('OTA105', 'Advanced Feeling Good About Your Job'),
('PTA102',  'Omega Advanced Muscles 101'),
('PTA103',  'Super Advanced Muscles 101'),
('PTA104',  'Giga Advanced Muscles 101'),
('PTA105',  'Omega Advanced Muscles 101'),
('VET102', 'Advanced All About Monkeys'),
('VET103', 'Super Advanced All About Monkeys'),
('VET104', 'Giga Advanced All About Monkeys'),
('VET105', 'Omega Advanced All About Monkeys');



insert into Courses_Prereq 
VALUES 
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CPT104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ACC104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ADM104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'AMT104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BAK104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'BIS104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CET101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CET102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CET103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CET104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CET105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CET104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'CAD104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'IST101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'IST102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'IST103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'IST104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'IST105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'IST104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'GEN104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MGT104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MET101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MET102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MET103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MET104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'MET105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MET104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'MAT101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'NSM104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'OTA104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ECO102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'PTA104')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'VET101'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'ENG101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'VET102'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET101')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'VET103'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET102')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'VET104'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET103')),
((SELECT Course_ID FROM Courses WHERE Course_ID = 'VET105'), (SELECT Course_ID FROM Courses WHERE Course_ID = 'VET104'));